-- ==========================================================================
-- Shipment Profit Calculator - Schema
--
-- Normalized (3NF) relational model:
--   shipment    : one row per shipment
--   income      : the customer payment recorded for a shipment (1 per shipment)
--   cost        : a service-provision cost for a shipment (at most 1 BASE + 1 ADDITIONAL per shipment)
--   profit_loss : the calculated, persisted result for a shipment (1 per shipment)
--
-- Calculating profit again for the same shipment updates its income/cost
-- rather than adding new ones, so the unique constraints below make that
-- invariant impossible to violate even if the application layer has a bug.
--
-- No separate CREATE INDEX statements: a UNIQUE constraint is backed by a
-- unique index automatically, and for cost's composite UNIQUE(shipment_id,
-- cost_type), the leading column means shipment_id-only lookups already use
-- that index too. The unique constraints already provide the indexes
-- supporting every lookup pattern the application uses.
-- ==========================================================================

DROP TABLE IF EXISTS profit_loss;
DROP TABLE IF EXISTS cost;
DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS shipment;

CREATE TABLE shipment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_code VARCHAR(50)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_shipment_code UNIQUE (shipment_code)
);

CREATE TABLE income (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id  BIGINT         NOT NULL,
    amount       DECIMAL(12,2)  NOT NULL,
    description  VARCHAR(255),
    created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_income_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT chk_income_amount CHECK (amount >= 0),
    CONSTRAINT uq_income_shipment UNIQUE (shipment_id)
);

CREATE TABLE cost (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id  BIGINT         NOT NULL,
    cost_type    VARCHAR(20)    NOT NULL,
    amount       DECIMAL(12,2)  NOT NULL,
    description  VARCHAR(255),
    created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cost_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT chk_cost_amount CHECK (amount >= 0),
    CONSTRAINT chk_cost_type CHECK (cost_type IN ('BASE', 'ADDITIONAL')),
    CONSTRAINT uq_cost_shipment_type UNIQUE (shipment_id, cost_type)
);

CREATE TABLE profit_loss (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id     BIGINT         NOT NULL,
    total_income    DECIMAL(12,2)  NOT NULL,
    total_costs     DECIMAL(12,2)  NOT NULL,
    profit_or_loss  DECIMAL(12,2)  NOT NULL,
    calculated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_profitloss_shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT uq_profitloss_shipment UNIQUE (shipment_id)
);
